### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lagden** [TExTecnologia/area-cliente-front#1]
- [x] Add slug na routa
- [x] Criar landpage @lagden 
- [x] Usar `window.atob` para fazer decode base64 do JWT do parte do payload - splita e pega o [1]

**Comment by lagden** [comment]
O código da landpage: http://codepen.io/lagden/pen/rWWvXy?editors=1100#0
